### PR TITLE
Change hours to minutes in all languages.

### PR DESCRIPTION
**Pull request by josikie**
Why?

For issue from Website: https://github.com/litecoin-foundation/litewallet.io/issues/63

The word "hours" should be "minutes" because we count it as minutes once the time inside one month before halving days. Previously, it was hours because we count it as hours once the time inside two months. Also, I saw on the litecoinhalf, the halving time is advanced by one day. So, we also change the date.

After this pr accepted and our library has new release, then the next step to fixed the bug is change library version on our website

### CODE REVIEW

**Review by vsima — APPROVED** [review]

**Comment by Patrick-t-mcdermott** [comment]
Right now litewallet.io for me is showing 22754 hours. I don't think that is correct.

**Review by Patrick-t-mcdermott — COMMENTED** [review]
whether hours or minutes is desired; Litewallet.io is showing 22571 HOURS. I think it is supposed to say minutes.

**Comment by josikie** [comment]
Hello @Patrick-t-mcdermott 

That's why I made this pr, to change the hours to Minutes.

The code does not automatically change the live website (litewallet.io). This pull request contains code that needs to be merged into our library, and it hasn't been merged. After the merge, our library should be published as a new version. Lastly, to make changes to our live website (litewallet.io), we need to update the library version of our website. I can't update the library version of our website if this pull request hasn't been merged and the new version of our library hasn't been published.

**Comment by Patrick-t-mcdermott** [comment]
Oh ok. I was confused. I don't know that kind of coding stuff. If that is really time consuming maybe a statement like "the halving is coming soon" and a link to view countdown would suffice.

**Comment by josikie** [comment]
It's ok and that's a good idea @Patrick-t-mcdermott, let me know if you have any other questions. We do the halving countdown because the halving countdown adds beauty to our website.

**Review by kcw-grunt — CHANGES_REQUESTED** [review]
@josikie  This is a correct fix. But, its not practical.
We will never be precise enough to set the halving to the minute.  So the fix should probably be going in the opposite direction....so showing back to days.

**Comment by josikie** [comment]
Ok, noted! @kcw-grunt

**Comment by josikie** [comment]
Will close this pr and make new one

**Comment by josikie** [comment]
Hello @kcw-grunt!
It's fixed

**Review by kcw-grunt — APPROVED** [review]
Excellent...going to the the site next

**Pull request merged**
