### PR TITLE
🥳[Feature] Add id, tr and de

### PR DESCRIPTION
**Pull request by josikie**
Added Bahasa Indonesia (id), Turkish (tr), and Germany (DE).

### CODE REVIEW

**Review by kcw-grunt — APPROVED** [review]
LGTM
@josikie you should convert this PR to ready.

**Comment by kcw-grunt** [comment]
@josikie you should convert this PR to ready.

**Comment by josikie** [comment]
Thank you! @kcw-grunt 
Yesterday, it was only Indonesian, now it is ready with Turkish and Germany.

**Comment by kcw-grunt** [comment]
Yes!  This time I'll do it. But next time (normally) you will merge yourself

> LGTM @josikie you should convert this PR to ready.

**Comment by josikie** [comment]
Ok, nice! Thanks @kcw-grunt

**Pull request merged**
